name: Scala CI

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Choose the OS for the CI runner (you can choose windows-latest or macos-latest)

    steps:
      # Checkout the code from your GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Scala
      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          scala-version: '2.13.8'  # Replace with your Scala version

      # Set up SBT (Scala build tool)
      - name: Set up SBT
        run: |
          curl -sSL https://get.sdkman.io | bash
          source $HOME/.sdkman/bin/sdkman-init.sh
          sdk install sbt

      # Change directory to 'uno' where build.sbt is located
      - name: Change to uno directory
        run: cd uno

      # Compile and test the Scala project
      - name: run tests
        run: sbt clean test
        working-directory: ./uno

      - name: Package jar
        run: sbt clean package
        working-directory: ./uno

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.4
        #with:
         # github-token: ${{ secrets.GITHUB_TOKEN }}
        #env:
         # COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}