name: Scala CI

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'



      - name: Set JAVA_HOME
        run: |
          echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
          echo "JAVA_HOME is set to: $JAVA_HOME"

      - name: Setup sbt
        uses: olafurpg/setup-scala@v14
        with:
          scala-version: '3.3.1'

      - name: Check Java version
        run: java -version

      - name: Compile and test with coverage
        run: sbt clean coverage test coverageReport
          #working-directory: ./UNO

          #  - name: Upload coverage data to Coveralls
          #run: sbt coverageAggregate coveralls
          #env:
          #  COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #  COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}

          #- name: Coveralls GitHub Action
          # uses: coverallsapp/github-action@v2.3.4
        #with:
        # path-to-lcov: ./UNO/target/scala-3.3.1/scoverage-report/scoverage.xml
        # env:
        #  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Upload coverage data to Coveralls
        uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./target/scala-3.3.1/scoverage-report/scoverage.xml
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}



      - name: Package jar
        run: sbt package
        #working-directory: ./UNO

     # - name: Upload coverage data to Coveralls
     #   run: sbt coverageReport coveralls
     #   env:
     #     COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     #     COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}
