name: Scala CI

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Scala
      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          scala-version: '3.5.1'

      # Set up SBT (Scala build tool)
      - name: Set up SBT
        run: |
          curl -sSL https://get.sdkman.io | bash
          source $HOME/.sdkman/bin/sdkman-init.sh
          sdk install sbt

      # Change directory to 'uno' where build.sbt is located
      #- name: Change to uno directory
       # run: cd uno

      - name: Compile and test with coverage
        run: sbt clean coverage test coverageReport coverageAggregate
        working-directory: ./uno

      #- name: Compile and test
       # run: sbt clean coverage test
        #working-directory: ./uno

      # Compile and test the Scala project
    #  - name: run tests
     #   run: sbt clean test
      #  working-directory: ./uno

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.4
        with:
          path-to-lcov: ./uno/target/scala-3.3.1/scoverage-report/scoverage.xml
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Package jar
        run: sbt clean package
        working-directory: ./uno


 # run_tests:
  #  runs-on: ubuntu-latest
   # steps:
    #  - uses: actions/checkout@v2
     # - name: Build Project and export Coverage
      #  env:
       #   CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        #  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        #run: |
         # export CI_BRANCH="${GITHUB_REF#refs/heads/}"
          #sbt clean jacoco jacocoCoveralls
