name: Scala CI

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clear sbt and Java caches
        run: |
          rm -rf ~/.sbt
          rm -rf ~/.ivy2
          rm -rf ~/.coursier

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'



      - name: Set JAVA_HOME
        run: |
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "JAVA_HOME path is: $JAVA_HOME"

      - name: Setup sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      #- name: Setup Scala
      #  uses: olafurpg/setup-scala@v14
      #  with:
      #    scala-version: '3.3.1'

      - name: Check Java version
        run: java -version

      - name: Set JAVA_HOME for sbt
        run: |
          echo "JAVA_HOME=$JAVA_HOME" >> ~/.bashrc
          echo "export PATH=$JAVA_HOME/bin:$PATH" >> ~/.bashrc
          source ~/.bashrc
          java -version  

      - name: Compile and test with coverage
        run: sbt clean coverage test coverageReport

      - name: Upload coverage data to Coveralls
        uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./target/scala-3.3.1/scoverage-report/scoverage.xml
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}



      - name: Package jar
        run: sbt package

